// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// protoc-gen-go-http v2.1.4

package producer

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

type ProducerHTTPServer interface {
	SaveOrder(context.Context, *SaveOrderRequest) (*SaveOrderReply, error)
}

func RegisterProducerHTTPServer(s *http.Server, srv ProducerHTTPServer) {
	r := s.Route("/")
	r.POST("/order/save", _Producer_SaveOrder0_HTTP_Handler(srv))
}

func _Producer_SaveOrder0_HTTP_Handler(srv ProducerHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in SaveOrderRequest
		if err := ctx.Bind(&in.Order); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, "/api.producer.Producer/SaveOrder")
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.SaveOrder(ctx, req.(*SaveOrderRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*SaveOrderReply)
		return ctx.Result(200, reply)
	}
}

type ProducerHTTPClient interface {
	SaveOrder(ctx context.Context, req *SaveOrderRequest, opts ...http.CallOption) (rsp *SaveOrderReply, err error)
}

type ProducerHTTPClientImpl struct {
	cc *http.Client
}

func NewProducerHTTPClient(client *http.Client) ProducerHTTPClient {
	return &ProducerHTTPClientImpl{client}
}

func (c *ProducerHTTPClientImpl) SaveOrder(ctx context.Context, in *SaveOrderRequest, opts ...http.CallOption) (*SaveOrderReply, error) {
	var out SaveOrderReply
	pattern := "/order/save"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation("/api.producer.Producer/SaveOrder"))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in.Order, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}
