// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"dataproducer/internal/biz"
	"dataproducer/internal/conf"
	"dataproducer/internal/data"
	"dataproducer/internal/server"
	"dataproducer/internal/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

// Injectors from wire.go:

// initApp init kratos application.
func initApp(confServer *conf.Server, confData *conf.Data, registry *conf.Registry, logger log.Logger) (*kratos.App, func(), error) {
	asyncProducer := data.NewKafkaProducer(confData)
	dataData, cleanup, err := data.NewData(asyncProducer, confData, logger)
	if err != nil {
		return nil, nil, err
	}
	orderRepo := data.NewOrderRepo(dataData, logger)
	orderCase := biz.NewOrderCase(orderRepo, logger)
	orderService := service.NewOrderService(orderCase, logger)
	httpServer := server.NewHTTPServer(confServer, orderService, logger)
	grpcServer := server.NewGRPCServer(confServer, orderService, logger)
	registrar := data.NewRegistrar(registry)
	app := newApp(logger, httpServer, grpcServer, registrar)
	return app, func() {
		cleanup()
	}, nil
}
