// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// protoc-gen-go-http v2.1.4

package admin

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

type AdminHTTPServer interface {
	SearchOrder(context.Context, *SearchOrderRequest) (*SearchOrderReply, error)
}

func RegisterAdminHTTPServer(s *http.Server, srv AdminHTTPServer) {
	r := s.Route("/")
	r.POST("/order/search", _Admin_SearchOrder0_HTTP_Handler(srv))
}

func _Admin_SearchOrder0_HTTP_Handler(srv AdminHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in SearchOrderRequest
		if err := ctx.Bind(&in.Order); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, "/api.admin.Admin/SearchOrder")
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.SearchOrder(ctx, req.(*SearchOrderRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*SearchOrderReply)
		return ctx.Result(200, reply)
	}
}

type AdminHTTPClient interface {
	SearchOrder(ctx context.Context, req *SearchOrderRequest, opts ...http.CallOption) (rsp *SearchOrderReply, err error)
}

type AdminHTTPClientImpl struct {
	cc *http.Client
}

func NewAdminHTTPClient(client *http.Client) AdminHTTPClient {
	return &AdminHTTPClientImpl{client}
}

func (c *AdminHTTPClientImpl) SearchOrder(ctx context.Context, in *SearchOrderRequest, opts ...http.CallOption) (*SearchOrderReply, error) {
	var out SearchOrderReply
	pattern := "/order/search"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation("/api.admin.Admin/SearchOrder"))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in.Order, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}
