// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"dataproducer/internal/admin"
	"dataproducer/internal/admin/service"
	"dataproducer/internal/conf"
	"dataproducer/internal/data"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

// Injectors from wire.go:

// initApp init kratos application.
func initApp(server *conf.Server, confData *conf.Data, registry *conf.Registry, logger log.Logger) (*kratos.App, func(), error) {
	adminService := service.NewAdminService()
	httpServer := admin.NewHTTPServer(server, adminService, logger)
	grpcServer := admin.NewGRPCServer(server, adminService, logger)
	registrar := data.NewRegistry(registry)
	app := newApp(logger, httpServer, grpcServer, registrar)
	return app, func() {
	}, nil
}
